### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by zachzhao7** [ajparra/iRotAvg#2]
Hi, I am getting this error using the Kitti grayscale dataset. It displays this error after matches for frame 0 and frame 1. Here is the result:

K:
[718.856, 0, 607.1928;
 0, 718.856, 185.2157;
 0, 0, 1]
dist coefs:
[0, 0, 0, 0]
initialising database...
frame 0  -- runtimes: frame creation 0.090l; frame processing 0.001, rotavg 0.000
frame 1  -- runtimes: frame creation 0.075l; frame processing 0.483, rotavg 0.000
# matches for (0, 2)  =  254
Segmentation fault     
       
      
I am wondering if it is probably because I complied the code with OpenCV 3.3,  and I have to use OpenCV 4.0 instead. Thanks!

**Comment by ajparra** [comment]
Hi, can you provide me with more details?

Are you compiling in Linux?

By the way, have you tried with OpenCV 4? 


Cheers

**Comment by zachzhao7** [comment]
> Hi, can you provide me with more details?
> 
> Are you compiling in Linux?
> 
> By the way, have you tried with OpenCV 4?
> 
> Cheers

I debuged the code and found the program crushed after calculating the relative orientation using Eigen, and I believe there is a problem with the Eigen version. So I compiled the code with the latest Eigen version and it worked. Thanks!
Ps. It should work well with opencv 3 & 4, but not 2.

**Comment by ajparra** [comment]
Can you tell me which version were you using and which version are you using now? I want to edit the readme and makefile to prevent the same issue. Cheers

**Comment by zachzhao7** [comment]
A little bit wired..Actually I succeeded running in my docker container with Eigen 3.3.4 and 3.3.7. But I cannot ran in my original environment with any eigen versions. cannot figure out why... I think there should be no problem running in a clear system with eigen above 3.3 installed.
